# Generated by Django 5.2.7 on 2025-10-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
